name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Load environment variables
      run: |
        if [ -f .env ]; then
          export $(grep -v '^#' .env | xargs)
        fi

    - name: Build project
      run: dotnet publish -c Release -o out

    - name: Deploy to VPS
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -r out/* $USER@$HOST:/var/www/testapp
        ssh $USER@$HOST "sudo systemctl restart testapp"
